package com.wjj.cwz.entity;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// default package
// Generated 2011-9-24 13:59:21 by Hibernate Tools 3.3.0.GA

/**
 * Employee generated by hbm2java 物流入驻实体类
 */
@Entity
@Table(name = "c_logis_In", catalog = "cwz")
public class LogisIn extends BaseBean {

	/*
	 * 1.上传营业执照 2.物流运输企业上传《道路运输许可证》 3.组织机构代码证 4.税务登记证
	 */
	private String buslice; // 营业执照
	
	private String buslicePic;// 营业执照图片名

	private String roadTranPer;// 道路运输许可证
	private String roadTranPerPic;// 道路运输许可证图片名

	private String orgCode;// 组织机构代码证
	private String orgCodePic;// 组织机构代码证图片

	private String taxCode;// 税务登记证号码
	private String taxCodePic;// 税务登记证号码

	//必需是要有对应的企业用户才可以申请入驻
	private User user;
	
	
	//物流厂商创建时间
	private Date createTime;
	
	//公司审批具体时间
	private Date checkTime;
	
	
	
	

	@Column(name = "buslice", length = 50)
	public String getBuslice() {
		return buslice;
	}

	public void setBuslice(String buslice) {
		this.buslice = buslice;
	}

	@Column(name = "buslicepic", length = 150)
	public String getBuslicePic() {
		return buslicePic;
	}

	public void setBuslicePic(String buslicePic) {
		this.buslicePic = buslicePic;
	}

	@Column(name = "roadtranper", length = 50)
	public String getRoadTranPer() {
		return roadTranPer;
	}

	public void setRoadTranPer(String roadTranPer) {
		this.roadTranPer = roadTranPer;
	}

	@Column(name = "roadtranperpic", length = 150)
	public String getRoadTranPerPic() {
		return roadTranPerPic;
	}

	public void setRoadTranPerPic(String roadTranPerPic) {
		this.roadTranPerPic = roadTranPerPic;
	}

	@Column(name = "orgcode", length = 50)
	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	@Column(name = "orgcodepic", length = 150)
	public String getOrgCodePic() {
		return orgCodePic;
	}

	public void setOrgCodePic(String orgCodePic) {
		this.orgCodePic = orgCodePic;
	}

	@Column(name = "taxcode", length = 50)
	public String getTaxCode() {
		return taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "taxcodepic", length = 150)
	public String getTaxCodePic() {
		return taxCodePic;
	}

	public void setTaxCodePic(String taxCodePic) {
		this.taxCodePic = taxCodePic;
	}

	
	@OneToOne(cascade = CascadeType.ALL)   
	@JoinColumn(name="user_id")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "create_time")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "check_time")
	@Temporal(TemporalType.TIMESTAMP)
	public   Date getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}



}
