package com.wjj.cwz.entity;

// default package
// Generated 2011-9-24 13:59:21 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "c_user", catalog = "cwz")
// @Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class User extends BaseBean {

	private String userCode;// 注册时，会员名即为userCode
	private String pasword;
	private String userName;// 当为企业用户时,username表示公司名，当为个人用户时,username表示个人姓名

	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	private String userType;// 目前主要两种，企业用户、个人用户
	private String userPhone;// 手机号码
	private String userEmail;// 电子邮箱
	
	//注册时间 
	private Date  createTime;
	
	//物流入驻标识,1表示入驻了，0表示未处理,默认未入驻
	private String logisIn="0";

	@Column(name = "user_type", length = 50)
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "user_phone", length = 50)
	public String getUserPhone() {
		return userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_email", length = 50)
	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public User() {
	}

	@Column(name = "user_code", length = 50)
	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "pasword", length = 50)
	public String getPasword() {
		return pasword;
	}

	public void setPasword(String pasword) {
		this.pasword = pasword;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	@Column(name="create_time")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "login_in", length = 50)
	public String getLogisIn() {
		return logisIn;
	}

	public void setLogisIn(String logisIn) {
		this.logisIn = logisIn;
	}

}
